

export const AnimeTitle = [
    {id:1 ,path: '../../../AnimeImges/original_2.jpg', title: 'Ван Пис ', status: "онгоинг"},
    {id:2 ,path: '../../../AnimeImges/original_1.jpg', title: 'Поднятие уровня в одиночку', status: "онгоинг"},
    {id:3 ,path: '../../../AnimeImges/original_3.jpg', title: 'Монолог фармацефта', status: "онгоинг"},
    {id:4 ,path: '../../../AnimeImges/original_4.jpg', title: 'Слабейшая укротительница в путешествии по сбору питомцев', status: "онгоинг"},
    {id:5 ,path: '../../../AnimeImges/original_5.jpg', title: 'Ведьма и чудовище', status: "онгоинг"},
    {id:6 ,path: '../../../AnimeImges/original_6.jpg', title: 'Несносные пришельцы (2024) 2 сезон', status: "онгоинг"},
    {id:7 ,path: '../../../AnimeImges/original_7.jpg', title: 'Становясь волшебницей', status: "онгоинг"},
    {id:8 ,path: '../../../AnimeImges/original_8.jpg', title: 'Добро пожаловать в класс превосходства 3 Сезон', status: "онгоинг"},
    {id:9 ,path: '../../../AnimeImges/original_9.jpg', title: 'Королева со скальпелем', status: "онгоинг"},
    {id:10 ,path: '../../../AnimeImges/original_10.jpg', title: 'Досанко-гяру чудо как милы', status: "онгоинг"},
    {id:11 ,path: '../../../AnimeImges/original_2.jpg', title: 'Ван Пис ', status: "онгоинг"},
    {id:12 ,path: '../../../AnimeImges/original_1.jpg', title: 'Поднятие уровня в одиночку', status: "онгоинг"},
    {id:13 ,path: '../../../AnimeImges/original_3.jpg', title: 'Монолог фармацефта', status: "онгоинг"},
    {id:14 ,path: '../../../AnimeImges/original_4.jpg', title: 'Слабейшая укротительница в путешествии по сбору питомцев', status: "онгоинг"},
    {id:15 ,path: '../../../AnimeImges/original_5.jpg', title: 'Ведьма и чудовище', status: "онгоинг"},
    {id:16 ,path: '../../../AnimeImges/original_6.jpg', title: 'Несносные пришельцы (2024) 2 сезон', status: "онгоинг"},
    {id:17 ,path: '../../../AnimeImges/original_7.jpg', title: 'Становясь волшебницей', status: "онгоинг"},
    {id:18 ,path: '../../../AnimeImges/original_8.jpg', title: 'Добро пожаловать в класс превосходства 3 Сезон', status: "онгоинг"},
    {id:19 ,path: '../../../AnimeImges/original_9.jpg', title: 'Королева со скальпелем', status: "онгоинг"},
    {id:20 ,path: '../../../AnimeImges/original_10.jpg', title: 'Досанко-гяру чудо как милы', status: "онгоинг"},
    {id:21 ,path: '../../../AnimeImges/original_2.jpg', title: 'Ван Пис ', status: "онгоинг"},
    {id:22 ,path: '../../../AnimeImges/original_1.jpg', title: 'Поднятие уровня в одиночку', status: "онгоинг"},
    {id:23 ,path: '../../../AnimeImges/original_3.jpg', title: 'Монолог фармацефта', status: "онгоинг"},
    {id:24 ,path: '../../../AnimeImges/original_4.jpg', title: 'Слабейшая укротительница в путешествии по сбору питомцев', status: "онгоинг"},
    {id:25 ,path: '../../../AnimeImges/original_5.jpg', title: 'Ведьма и чудовище', status: "онгоинг"},
    {id:26 ,path: '../../../AnimeImges/original_6.jpg', title: 'Несносные пришельцы (2024) 2 сезон', status: "онгоинг"},
    {id:27 ,path: '../../../AnimeImges/original_7.jpg', title: 'Становясь волшебницей', status: "онгоинг"},
    {id:28 ,path: '../../../AnimeImges/original_8.jpg', title: 'Добро пожаловать в класс превосходства 3 Сезон', status: "онгоинг"},
    {id:29 ,path: '../../../AnimeImges/original_9.jpg', title: 'Королева со скальпелем', status: "онгоинг"},
    {id:30 ,path: '../../../AnimeImges/original_8.jpg', title: 'Добро пожаловать в класс превосходства 3 Сезон', status: "онгоинг"},
    {id:31 ,path: '../../../AnimeImges/original_9.jpg', title: 'Королева со скальпелем', status: "онгоинг"},
    {id:32 ,path: '../../../AnimeImges/original_10.jpg', title: 'Досанко-гяру чудо как милы', status: "онгоинг"},
    {id:33 ,path: '../../../AnimeImges/original_2.jpg', title: 'Ван Пис ', status: "онгоинг"},
    {id:34 ,path: '../../../AnimeImges/original_1.jpg', title: 'Поднятие уровня в одиночку', status: "онгоинг"},
    {id:35 ,path: '../../../AnimeImges/original_3.jpg', title: 'Монолог фармацефта', status: "онгоинг"},
    {id:36 ,path: '../../../AnimeImges/original_4.jpg', title: 'Слабейшая укротительница в путешествии по сбору питомцев', status: "онгоинг"},
    {id:37 ,path: '../../../AnimeImges/original_5.jpg', title: 'Ведьма и чудовище', status: "онгоинг"},
    {id:38 ,path: '../../../AnimeImges/original_6.jpg', title: 'Несносные пришельцы (2024) 2 сезон', status: "онгоинг"},
    {id:39 ,path: '../../../AnimeImges/original_7.jpg', title: 'Становясь волшебницей', status: "онгоинг"},
    {id:40 ,path: '../../../AnimeImges/original_8.jpg', title: 'Добро пожаловать в класс превосходства 3 Сезон', status: "онгоинг"},
    {id:41 ,path: '../../../AnimeImges/original_9.jpg', title: 'Королева со скальпелем', status: "онгоинг"},
    

]